select * from npatil09.Gender
select * from npatil09.Race
select * from npatil09.Addresses
select * from npatil09.PersonInformation
select * from npatil09.StudentStatus
select * from npatil09.StudentType
select * from npatil09.StudentInformation
select * from npatil09.SemesterText
select * from npatil09.SemesterInfo
select * from npatil09.ClassRoom
select * from npatil09.Level
select * from npatil09.Department
select * from npatil09.SubCourses
select * from npatil09.CourseCatalogue
select * from npatil09.CourseSchedule
select * from npatil09.EnrollmentStatus
select * from npatil09.CourseEnrollment
select * from npatil09.College
select * from npatil09.DegreeOfStudy
select * from npatil09.studentAreaOfStudy
select * from npatil09.Prerequisites
select * from npatil09.EmployeeInfo
select * from npatil09.BenefitType
select * from npatil09.BenefitCoverage
select * from npatil09.EmployeeBenefits
select * from npatil09.JobTypeDetail
select * from npatil09.JobDescription 
select * from npatil09.EmployeeandJobs
select * from npatil09.DailySchedule
select * from npatil09.EmployeeAndCourse

